settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: QuestionStore
  path: /go/src/github.com/Amakuchisan/QuestionStore
  commands:
    install:
      status: true
      method: go build -o /go/src/github.com/Amakuchisan/QuestionStore/bin/qs
    run:
      status: true
      method: /go/src/github.com/Amakuchisan/QuestionStore/bin/qs
  watcher:
    extensions:
    - go
    - html
    - css
    - js
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
