version: '3'

services:
  app:
    container_name: tts-container
    tty: true
    stdin_open: true
    build: .
    ports:
      - "1323:1323"
    depends_on:
      - db
    links:
      - db

  db:
    container_name: mysql-container
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: tts
      MYSQL_USER: tts
      MYSQL_PASSWORD: tts
      MYSQL_DATABASE: tts
    ports:
       - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10 
    volumes:
      - ./db:/docker-entrypoint-initdb.d
