version: '3.8'

services:
  app:
    container_name: qs-container
    tty: true
    stdin_open: true
    build:
      context: .
      target: builder
    command: realize start --run
    ports:
      - "1323:1323"
    environment:
      QS_ENV: development
    depends_on:
      - db
    volumes:
      - ./:/go/src/github.com/Amakuchisan/QuestionStore

  db:
    container_name: mysql-container
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: qs
      MYSQL_USER: qs
      MYSQL_PASSWORD: qs
      MYSQL_DATABASE: qs
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10 
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
